### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by hadiasghari** [datarights/DataInSight#139]
1. Local build fails on ```docker-compose -f docker-compose-development.yml up```   output below).

2. Travis also reports a build error: 
https://travis-ci.org/datarights/DataInSight

```
$ docker-compose -f docker-compose-development.yml up
WARNING: The SENDGRID_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The SENDGRID_PASSWORD variable is not set. Defaulting to a blank string.
Creating network "datainsight_default" with the default driver
Pulling db (postgres:10.3)...
Trying to pull repository docker.io/library/postgres ... 
sha256:1c2cc88d0573332ff1584f72f0cf066b1db764166786d85f5541b3fc1e362aee: Pulling from docker.io/library/postgres
Digest: sha256:1c2cc88d0573332ff1584f72f0cf066b1db764166786d85f5541b3fc1e362aee
Status: Downloaded newer image for docker.io/postgres:10.3
Creating datainsight_db_1 ... done
Creating datainsight_app_1 ... done
Attaching to datainsight_db_1, datainsight_app_1
db_1   | chown: cannot read directory '/var/lib/postgresql/data': Permission denied
datainsight_db_1 exited with code 1
app_1  | /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/definition.rb:33:in `build': /usr/src/app/Gemfile not found (Bundler::GemfileNotFound)
app_1  | 	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:135:in `definition'
app_1  | 	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler.rb:101:in `setup'
app_1  | 	from /usr/local/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
app_1  | 	from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
app_1  | 	from /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
app_1  | 	from /usr/local/bundle/bin/rake:27:in `<main>'
datainsight_app_1 exited with code 1

```

**Comment by mani47** [comment]
For some reason I can not reproduce the docker issue, but I found this bug report: https://github.com/docker-library/postgres/issues/116

Can you please try solutions suggested here: https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

Also fixed the Travis issue.

**Comment by hadiasghari** [comment]
@mani47 thanks for fixing Travis. Figured the other one out, had to do with Fedora's SELinux protections, temporary turned them off and the Docker works.
